name: Build latex to PDF

on:
  push:
    paths:
      - '**.latex'
      - .github/workflows/ci.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        uses: addnab/docker-run-action@v3
        with:
          image: janmasrovira/texlive:2025-custom
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            latexmk -pdf cv

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf

      - name: Upload PDF to pages
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
