name: Build Typst to PDF

on:
  push:
    paths:
      - '**.typ'
      - .github/workflows/ci.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Typst to PDF
        uses: addnab/docker-run-action@v3
        with:
          image: 123marvin123/typst:0.13.1
          options: -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            typst compile cv.typ
            mkdir public
            mv cv.pdf public/

      - name: Upload pdf artifact
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
